const { cmd, commands } = require("../command");
const config = require("../config");
const axios = require('axios'); 

const lastHelpMessage = new Map();
const HELP_IMG_URL = "https://raw.githubusercontent.com/sasiyamd3-cell/Bot-logo/refs/heads/main/1778591680024.png";

// --- 🖼️ IMAGE PRE-LOAD LOGIC ---
let cachedHelpImage = null;

async function preLoadHelpImage() {
    try {
        const response = await axios.get(HELP_IMG_URL, { responseType: 'arraybuffer' });
        cachedHelpImage = Buffer.from(response.data);
        console.log("✅ [CACHE] NEXUS-MD Help image pre-loaded.");
    } catch (e) {
        console.error("❌ [CACHE] Failed to pre-load help image:", e.message);
        cachedHelpImage = null;
    }
}

preLoadHelpImage();

cmd({
    pattern: "help",
    alias: ["bothelp", "info", "උදව්"],
    category: "main",
    react: "❓",
    desc: "NEXUS-MD සහය මධ්‍යස්ථානය සහ විධාන පිළිබඳ විස්තර ලබා දෙයි.",
    filename: __filename,
}, async (zanta, mek, m, { from, reply, args, pushname, userSettings }) => {
    try {
        const settings = userSettings || global.CURRENT_BOT_SETTINGS || {};
        const botName = "𝐍 𝐄 𝐗 𝐔 𝐒 - 𝐌 𝐃";
        const ownerName = "Sasiya MD";
        const prefix = config.PREFIX || ".";

        // --- 🔍 COMMAND INFO LOGIC (.help <cmd> සඳහා) ---
        if (args[0] && isNaN(args[0])) {
            const searchCmd = args[0].toLowerCase().trim();

            const command = commands.find(c => 
                c.pattern.toLowerCase() === searchCmd || 
                (c.alias && c.alias.map(a => a.toLowerCase()).includes(searchCmd))
            );

            if (command) {
                let cmdInfo = `*✨ COMMAND INFORMATION ✨*\n\n` +
                              `📑 *Command:* ${prefix}${command.pattern}\n` +
                              `📋 *Alias:* ${command.alias ? command.alias.join(", ") : "None"}\n` +
                              `🗂️ *Category:* ${command.category.toUpperCase()}\n` +
                              `📝 *Description:* ${command.desc || "No description provided."}\n\n` +
                              `> *Generated by ${botName} Support*`;

                return await zanta.sendMessage(from, { 
                    text: cmdInfo,
                    contextInfo: {
                        externalAdReply: {
                            title: `${botName} Help Assistant`,
                            body: `Command Details: ${searchCmd}`,
                            thumbnail: cachedHelpImage,
                            sourceUrl: "https://sasinda-sait-5c33c9cc740d.herokuapp.com",
                            mediaType: 1,
                            renderLargerThumbnail: false
                        }
                    }
                }, { quoted: mek });
            } else {
                return reply(`❌ *'${searchCmd}'* නමින් විධානයක් සොයාගත නොහැක.`);
            }
        }

        // --- 📂 Selection Logic ---
        const selection = args[0]; 

        if (selection === "1") {
            let devMsg = `*👨‍💻 Bot Developer Details*\n\n` +
                         `👤 *Name:* ${ownerName}\n` +
                         `🛠️ *Team:* Developer Nexus (TRX)\n` +
                         `🌍 *Country:* Sri Lanka\n` +
                         `🔗 *Pair Site:* https://sasinda-sait-5c33c9cc740d.herokuapp.com\n\n` +
                         `> *Powered by Developer Nexus Team*`;
            return reply(devMsg);
        }

        if (selection === "2") {
            let featMsg = `*🚀 ${botName} Features Summary*\n\n` +
                          `📥 *Download:* FB, YT, TikTok, APK, MediaFire\n` +
                          `🛠️ *Tools:* Logo Gen, Bg Remove, IP Tracker\n` +
                          `🛡️ *Security:* Anti-Link, Group Protection\n\n` +
                          `_සම්පූර්ණ ලැයිස්තුවට *${prefix}menu* භාවිතා කරන්න._`;
            return reply(featMsg);
        }

        if (selection === "3") {
            let contactMsg = `*📞 Contact Us*\n\n` +
                             `ඔබට කිසියම් ගැටළුවක් ඇත්නම් අප හා සම්බන්ධ වන්න.\n\n` +
                             `🔗 *Official Pair Site:* https://sasinda-sait-5c33c9cc740d.herokuapp.com\n\n` +
                             `_Thank you for using ${botName}!_`;
            return reply(contactMsg);
        }

        // --- 📂 MAIN HELP MESSAGE ---
        let mainHelp = `*👋 Hello ${pushname}!* \n\n` +
                       `*✨ ${botName} Support System ✨*\n\n` +
                       `අදාළ අංකය Reply කිරීමෙන් වැඩි විස්තර ලබාගන්න:\n\n` +
                       `┌───⊷\n` +
                       `│ 1️⃣ *Developer Info*\n` +
                       `│ 2️⃣ *Features Overview*\n` +
                       `│ 3️⃣ *Contact & Pairing*\n` +
                       `└───⊷\n\n` +
                       `💡 *Tip:* විධානයක විස්තර බැලීමට *${prefix}help <command>* ලෙස යොමු කරන්න.\n\n` +
                       `> *© 2026 Developer Nexus Team*`;

        let imageToDisplay = (settings.botImage && settings.botImage !== "null") ? { url: settings.botImage } : (cachedHelpImage || { url: HELP_IMG_URL });

        const sentHelp = await zanta.sendMessage(from, { 
            image: imageToDisplay, 
            caption: mainHelp,
            contextInfo: {
                mentionedJid: [m.sender],
                forwardingScore: 999,
                isForwarded: true,
                externalAdReply: {
                    title: `${botName} Official Support`,
                    body: `Developer: ${ownerName}`,
                    thumbnail: cachedHelpImage,
                    sourceUrl: "https://sasinda-sait-5c33c9cc740d.herokuapp.com",
                    mediaType: 1,
                    renderLargerThumbnail: false
                }
            }
        }, { quoted: mek });

        lastHelpMessage.set(from, sentHelp.key.id);

    } catch (e) {
        console.error(e);
        reply("❌ Error: " + e.message);
    }
});

module.exports = { lastHelpMessage };
