const { cmd, commands } = require("../command");
const config = require("../config");
const axios = require('axios'); 

const lastHelpMessage = new Map();
const HELP_IMG_URL = "https://raw.githubusercontent.com/sasiyamd3-cell/Bot-logo/refs/heads/main/1778591680024.png";

// --- 🖼️ IMAGE PRE-LOAD LOGIC ---
let cachedHelpImage = null;

async function preLoadHelpImage() {
    try {
        const response = await axios.get(HELP_IMG_URL, { responseType: 'arraybuffer' });
        cachedHelpImage = Buffer.from(response.data);
        console.log("✅ [CACHE] Help image pre-loaded successfully.");
    } catch (e) {
        console.error("❌ [CACHE] Failed to pre-load help image:", e.message);
        cachedHelpImage = null;
    }
}

preLoadHelpImage();

cmd({
    pattern: "help",
    alias: ["bothelp", "info", "උදව්"],
    category: "main",
    react: "❓",
    desc: "බොට් සහාය මධ්‍යස්ථානය සහ විධාන පිළිබඳ විස්තර ලබා දෙයි.",
    filename: __filename,
}, async (zanta, mek, m, { from, reply, args, pushname, userSettings }) => {
    try {
        const settings = userSettings || global.CURRENT_BOT_SETTINGS || {};
        const botName = "𝐍 𝐄 𝐗 𝐔 𝐒 - 𝐌 𝐃";
        const prefix = config.PREFIX || ".";

        // --- 🔍 COMMAND INFO LOGIC (.help <cmd> සඳහා) ---
        if (args[0] && isNaN(args[0])) {
            const searchCmd = args[0].toLowerCase().trim();

            // Command pattern එක හෝ alias එක පරීක්ෂා කිරීමේ නිවැරදි ක්‍රමය
            const command = commands.find(c => 
                c.pattern.toLowerCase() === searchCmd || 
                (c.alias && c.alias.map(a => a.toLowerCase()).includes(searchCmd))
            );

            if (command) {
                let cmdInfo = `*✨ COMMAND INFORMATION ✨*\n\n` +
                              `📑 *Command:* ${prefix}${command.pattern}\n` +
                              `📋 *Alias:* ${command.alias ? command.alias.join(", ") : "නැත"}\n` +
                              `🗂️ *Category:* ${command.category.toUpperCase()}\n` +
                              `📝 *Description:* ${command.desc || "විස්තරයක් ලබා දී නැත."}\n\n` +
                              `> *Generated by ${botName} Support*`;

                return await zanta.sendMessage(from, { 
                    text: cmdInfo,
                    contextInfo: {
                        externalAdReply: {
                            title: `${botName} Help Assistant`,
                            body: `විස්තර: ${searchCmd}`,
                            thumbnail: cachedHelpImage,
                            sourceUrl: "https://sasinda-sait-5c33c9cc740d.herokuapp.com",
                            mediaType: 1,
                            renderLargerThumbnail: false
                        }
                    }
                }, { quoted: mek });
            } else {
                // සොයන command එක නැතිනම් දෙන පණිවිඩය
                return reply(`❌ *'${searchCmd}'* නමින් command එකක් සොයාගත නොහැක.`);
            }
        }

        // --- 📂 1. අංකයක් Reply කළ විට (Selection Logic) ---
        const selection = args[0]; 

        if (selection === "1") {
            let devMsg = `*👨‍💻 Bot Developer Details*\n\n` +
                         `👤 *Name:* Sasiya MD\n` +
                         `🛠️ *Project:* NEXUS-MD\n` +
                         `🌍 *Country:* Sri Lanka\n` +
                         `🔗 *Pairing:* https://sasinda-sait-5c33c9cc740d.herokuapp.com\n\n` +
                         `> *Created with ❤️ by Sasiya*`;
            return reply(devMsg);
        }

        if (selection === "2") {
            let featMsg = `*🚀 ${botName} Features Summary*\n\n` +
                          `🖼️ *Media:* Getdp, Save status, Unlock view once\n` +
                          `🎶 *Download:* Song, YTmp4, FB, Tiktok, Apk\n` +
                          `🎨 *AI:* AI Image Gen, Remove Bg\n\n` +
                          `_සම්පූර්ණ ලැයිස්තුවට *${prefix}menu* භාවිතා කරන්න._`;
            return reply(featMsg);
        }

        if (selection === "3") {
            let contactMsg = `*📞 Contact Us*\n\n` +
                             `Have you any question?\n\n` +
                             `🔗 *Pairing Site:* https://sasinda-sait-5c33c9cc740d.herokuapp.com\n\n` +
                             `_Thank you for using ${botName}!_`;
            return reply(contactMsg);
        }

        // --- 📂 2. MAIN HELP MESSAGE ---
        let mainHelp = `*👋 හෙලෝ ${pushname}!* \n\n` +
                       `*✨ ${botName} සහය මධ්‍යස්ථානයට සාදරයෙන් පිළිගනිමු ✨*\n\n` +
                       `පහත විකල්ප තේරීමට අදාළ අංකය Reply කරන්න:\n\n` +
                       `┌───⊷\n` +
                       `│ 1️⃣ *Developer*\n` +
                       `│ 2️⃣ *Features Overview*\n` +
                       `│ 3️⃣ *Contact Details*\n` +
                       `└───⊷\n\n` +
                       `💡 *Tip:* ඕනෑම විධානයක විස්තර බැලීමට *${prefix}help <command>* යොමු කරන්න. (Ex: ${prefix}help fullpp)\n\n` +
                       `> *${botName} Support System*`;

        let imageToDisplay = (settings.botImage && settings.botImage !== "null") ? { url: settings.botImage } : (cachedHelpImage || { url: HELP_IMG_URL });

        const sentHelp = await zanta.sendMessage(from, { 
            image: imageToDisplay, 
            caption: mainHelp,
            contextInfo: {
                mentionedJid: [m.sender],
                forwardingScore: 999,
                isForwarded: true,
                externalAdReply: {
                    title: `${botName} Support Center`,
                    body: `Developer: Sasiya MD`,
                    thumbnail: cachedHelpImage,
                    sourceUrl: "https://sasinda-sait-5c33c9cc740d.herokuapp.com",
                    mediaType: 1,
                    renderLargerThumbnail: false
                }
            }
        }, { quoted: mek });

        lastHelpMessage.set(from, sentHelp.key.id);

    } catch (e) {
        console.error(e);
        reply("❌ Error: " + e.message);
    }
});

module.exports = { lastHelpMessage };
